#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# BRACE — generate a ready-to-apply brace-secret manifest
#
#   ./k8s/gen-secret.sh > /tmp/brace-secret.yaml
#   oc apply -f /tmp/brace-secret.yaml
#   shred -u /tmp/brace-secret.yaml     # or: rm -f
#
# Writes YAML to stdout and progress to stderr, so redirecting stdout
# gives you a clean manifest.
#
# Values you can pin via the environment (anything unset is generated):
#   BRACE_ADMIN_PASSWORD   bootstrap admin password
#   NAMESPACE              target namespace
# ═══════════════════════════════════════════════════════════════
set -euo pipefail

NAMESPACE="${NAMESPACE:-brace}"

say() { printf '%s\n' "$*" >&2; }

need() {
  command -v "$1" >/dev/null 2>&1 || { say "ERROR: '$1' is required but not installed."; exit 1; }
}
need openssl

# ── JWT signing key: 32 random bytes, hex ─────────────────────
JWT_SECRET="$(openssl rand -hex 32)"

# ── Fernet key: url-safe base64 of exactly 32 random bytes ────
# Prefer python+cryptography (authoritative); fall back to openssl.
FERNET=""
for PY in python3 python py; do
  if command -v "$PY" >/dev/null 2>&1; then
    FERNET="$("$PY" -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())' 2>/dev/null || true)"
    [ -n "$FERNET" ] && break
  fi
done
if [ -z "$FERNET" ]; then
  # base64url of 32 bytes == what Fernet.generate_key() produces
  FERNET="$(openssl rand 32 | openssl base64 -A | tr '+/' '-_')"
  say "note: generated the Fernet key with openssl (python cryptography not found)"
fi
# Sanity-check the shape Fernet requires, so a bad key never reaches the cluster
if [ "${#FERNET}" -ne 44 ]; then
  say "ERROR: generated encryption key is ${#FERNET} chars, expected 44. Aborting."
  exit 1
fi

ADMIN_PASSWORD="${BRACE_ADMIN_PASSWORD:-$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-20)}"
RUNNER_TOKEN="$(openssl rand -hex 32)"
# YAML-safe encoding also handles quotes/newlines in a supplied admin password.
JWT_B64="$(printf '%s' "$JWT_SECRET" | openssl base64 -A)"
FERNET_B64="$(printf '%s' "$FERNET" | openssl base64 -A)"
ADMIN_B64="$(printf '%s' "$ADMIN_PASSWORD" | openssl base64 -A)"
TOKEN_B64="$(printf '%s' "$RUNNER_TOKEN" | openssl base64 -A)"
ENDPOINT_B64="$(printf '{"1":{"url":"http://brace-runner-project-1.%s.svc.cluster.local:8090","token":"%s"}}' "$NAMESPACE" "$RUNNER_TOKEN" | openssl base64 -A)"

cat <<YAML
# Generated by k8s/gen-secret.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# CONTAINS LIVE SECRETS — apply it, then delete this file. Do not commit.
apiVersion: v1
kind: Secret
metadata:
  name: brace-secret
  namespace: ${NAMESPACE}
  labels:
    app: brace-rf-controller
type: Opaque
data:
  JWT_SECRET: "${JWT_B64}"
  BRACE_ENCRYPT_KEY: "${FERNET_B64}"
  BRACE_ADMIN_PASSWORD: "${ADMIN_B64}"
---
apiVersion: v1
kind: Secret
metadata:
  name: brace-runner-project-1
  namespace: ${NAMESPACE}
type: Opaque
data:
  token: "${TOKEN_B64}"
---
apiVersion: v1
kind: Secret
metadata:
  name: brace-runner-endpoints
  namespace: ${NAMESPACE}
type: Opaque
data:
  endpoints: "${ENDPOINT_B64}"
YAML

say ""
say "───────────────────────────────────────────────────────────"
say " brace-secret generated for namespace: ${NAMESPACE}"
say ""
say "   admin login password : ${ADMIN_PASSWORD}"
say ""
say "   Save that password now — it is not stored anywhere else."
say ""
say " Apply, then shred:"
say "   oc apply -f <file>  &&  shred -u <file>"
say "───────────────────────────────────────────────────────────"
